// Grid2Poster gallery — single-file vanilla JS. Edit freely.
//
// Data flow:
//   posters/manifest.json (generated by build_manifest.py)
//     -> render gallery cards
//     -> filters (region + theme) update the visible set
//     -> click card -> lightbox (zoom on click/wheel, drag to pan)
//     -> Download button -> direct file
//     -> SVG button -> direct file (only when an SVG exists)
//     -> Share button -> Web Share API, falls back to clipboard
//     -> URL hash (#<poster-id>) makes posters deep-linkable

const state = {
  posters: [],
  filters: { region: "all", theme: "all" },
  current: null,
  zoom: { scale: 1, x: 0, y: 0 },
};

const els = {
  gallery: document.getElementById("gallery"),
  regionFilter: document.getElementById("region-filter"),
  themeFilter: document.getElementById("theme-filter"),
  count: document.getElementById("count"),
  lightbox: document.getElementById("lightbox"),
  lightboxImg: document.getElementById("lightbox-img"),
  lightboxTitle: document.getElementById("lightbox-title"),
  lightboxStage: document.getElementById("lightbox-stage"),
  lightboxClose: document.getElementById("lightbox-close"),
  lightboxDownload: document.getElementById("lightbox-download"),
  lightboxSvg: document.getElementById("lightbox-svg"),
  lightboxShare: document.getElementById("lightbox-share"),
  lightboxPrev: document.getElementById("lightbox-prev"),
  lightboxNext: document.getElementById("lightbox-next"),
  toast: document.getElementById("toast"),
};

// Lazy-load card images via IntersectionObserver. Images get a real `src`
// only once they scroll within ~400px of the viewport, so a fresh page load
// fetches a handful of posters instead of all 80+.
const imgObserver = "IntersectionObserver" in window
  ? new IntersectionObserver(onIntersect, { rootMargin: "400px 0px", threshold: 0.01 })
  : null;

function onIntersect(entries, obs) {
  for (const entry of entries) {
    if (!entry.isIntersecting) continue;
    const img = entry.target;
    const src = img.dataset.src;
    if (src) {
      img.src = src;
      img.removeAttribute("data-src");
    }
    obs.unobserve(img);
  }
}

init();

async function init() {
  try {
    const res = await fetch("posters/manifest.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`manifest fetch failed: ${res.status}`);
    const data = await res.json();
    state.posters = data.posters || [];
  } catch (err) {
    els.gallery.innerHTML = `<p>Could not load posters/manifest.json. Run <code>python build_manifest.py</code> to generate it.</p>`;
    console.error(err);
    return;
  }
  renderFilters();
  renderGallery();
  bindLightbox();
  handleHash();
  window.addEventListener("hashchange", handleHash);
}

// --------- Filters ---------

function uniqueSorted(items, key) {
  const seen = new Map();
  for (const p of items) {
    if (!seen.has(p[key])) seen.set(p[key], p[`${key}_display`]);
  }
  return [...seen.entries()].sort((a, b) => a[1].localeCompare(b[1]));
}

function renderFilters() {
  const regions = uniqueSorted(state.posters, "region");
  const themes = uniqueSorted(state.posters, "theme");
  renderChips(els.regionFilter, regions, "region");
  renderChips(els.themeFilter, themes, "theme");
}

function renderChips(container, entries, kind) {
  container.innerHTML = "";
  container.appendChild(makeChip("all", "All", kind));
  for (const [value, label] of entries) {
    container.appendChild(makeChip(value, label, kind));
  }
}

function makeChip(value, label, kind) {
  const btn = document.createElement("button");
  btn.type = "button";
  btn.className = "chip" + (state.filters[kind] === value ? " active" : "");
  btn.textContent = label;
  btn.dataset.value = value;
  btn.dataset.kind = kind;
  btn.addEventListener("click", () => {
    state.filters[kind] = value;
    document
      .querySelectorAll(`.chip[data-kind="${kind}"]`)
      .forEach((c) => c.classList.toggle("active", c.dataset.value === value));
    renderGallery();
  });
  return btn;
}

// --------- Gallery ---------

function visiblePosters() {
  const { region, theme } = state.filters;
  return state.posters.filter(
    (p) => (region === "all" || p.region === region) && (theme === "all" || p.theme === theme)
  );
}

function renderGallery() {
  const items = visiblePosters();
  els.gallery.innerHTML = "";
  for (const p of items) els.gallery.appendChild(card(p));
  els.count.textContent = `${items.length} poster${items.length === 1 ? "" : "s"}`;
}

function card(p) {
  const wrap = document.createElement("article");
  wrap.className = "card";
  wrap.tabIndex = 0;
  wrap.setAttribute("role", "button");
  wrap.setAttribute("aria-label", `Open ${p.region_display} - ${p.theme_display}`);

  const imgWrap = document.createElement("div");
  imgWrap.className = "card-image";
  const img = document.createElement("img");
  img.loading = "lazy";
  img.decoding = "async";
  img.alt = `${p.region_display} transmission grid - ${p.theme_display} theme`;
  const src = `posters/${p.png || p.svg}`;
  if (imgObserver) {
    img.dataset.src = src;
    imgObserver.observe(img);
  } else {
    img.src = src;
  }
  imgWrap.appendChild(img);

  const body = document.createElement("div");
  body.className = "card-body";
  const title = document.createElement("h3");
  title.className = "card-title";
  title.textContent = p.region_display;
  const sub = document.createElement("p");
  sub.className = "card-sub";
  sub.textContent = p.theme_display;
  if (p.voltage_interpolation) {
    const dot = document.createElement("span");
    dot.className = "vinterp-dot";
    dot.title = "Voltage colors";
    sub.appendChild(dot);
  }
  body.appendChild(title);
  body.appendChild(sub);

  wrap.appendChild(imgWrap);
  wrap.appendChild(body);

  const open = () => openLightbox(p);
  wrap.addEventListener("click", open);
  wrap.addEventListener("keydown", (e) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      open();
    }
  });
  return wrap;
}

// --------- Lightbox ---------

function bindLightbox() {
  els.lightboxClose.addEventListener("click", closeLightbox);
  els.lightbox.addEventListener("click", (e) => {
    if (e.target === els.lightbox) closeLightbox();
  });
  document.addEventListener("keydown", (e) => {
    if (els.lightbox.hidden) return;
    if (e.key === "Escape") closeLightbox();
    else if (e.key === "ArrowRight") stepLightbox(1);
    else if (e.key === "ArrowLeft") stepLightbox(-1);
  });
  els.lightboxShare.addEventListener("click", shareCurrent);
  els.lightboxPrev.addEventListener("click", (e) => { e.stopPropagation(); stepLightbox(-1); });
  els.lightboxNext.addEventListener("click", (e) => { e.stopPropagation(); stepLightbox(1); });
  els.lightboxSvg.addEventListener("click", () => {
    if (state.current?.svg) triggerDownload(`posters/${state.current.svg}`, state.current.svg);
  });

  // Zoom on click, drag to pan, wheel to zoom.
  els.lightboxStage.addEventListener("click", (e) => {
    if (e.target.closest(".lightbox-bar")) return;
    if (e.target === els.lightboxImg) toggleZoom(e);
  });
  els.lightboxStage.addEventListener("wheel", onWheel, { passive: false });
  bindPan();
}

function openLightbox(p) {
  state.current = p;
  els.lightboxImg.src = `posters/${p.png || p.svg}`;
  els.lightboxImg.alt = `${p.region_display} - ${p.theme_display}`;
  els.lightboxTitle.innerHTML = "";
  const titleText = `${p.region_display} — ${p.theme_display}`;
  els.lightboxTitle.appendChild(document.createTextNode(titleText));
  if (p.voltage_interpolation) {
    const dot = document.createElement("span");
    dot.className = "vinterp-dot";
    dot.title = "Voltage colors";
    els.lightboxTitle.appendChild(dot);
  }
  els.lightboxDownload.href = `posters/${p.png || p.svg}`;
  els.lightboxDownload.setAttribute("download", p.png || p.svg);
  els.lightboxSvg.hidden = !p.svg;
  const multi = visiblePosters().length > 1;
  els.lightboxPrev.hidden = !multi;
  els.lightboxNext.hidden = !multi;
  resetZoom();
  els.lightbox.hidden = false;
  els.lightbox.setAttribute("aria-hidden", "false");
  document.body.style.overflow = "hidden";
  if (location.hash !== `#${p.id}`) history.replaceState(null, "", `#${p.id}`);
}

function closeLightbox() {
  els.lightbox.hidden = true;
  els.lightbox.setAttribute("aria-hidden", "true");
  document.body.style.overflow = "";
  state.current = null;
  if (location.hash) history.replaceState(null, "", location.pathname + location.search);
}

function stepLightbox(delta) {
  if (!state.current) return;
  const items = visiblePosters();
  const i = items.findIndex((p) => p.id === state.current.id);
  if (i === -1) return;
  const next = items[(i + delta + items.length) % items.length];
  if (next) openLightbox(next);
}

function handleHash() {
  const id = location.hash.replace(/^#/, "");
  if (!id) {
    if (!els.lightbox.hidden) closeLightbox();
    return;
  }
  const p = state.posters.find((x) => x.id === id);
  if (p) openLightbox(p);
}

// --------- Zoom & pan ---------

function applyTransform() {
  const { scale, x, y } = state.zoom;
  els.lightboxImg.style.transform = `translate(${x}px, ${y}px) scale(${scale})`;
}

function resetZoom() {
  state.zoom = { scale: 1, x: 0, y: 0 };
  els.lightboxStage.classList.remove("zoomed", "panning");
  applyTransform();
}

function toggleZoom(e) {
  if (state.zoom.scale > 1) {
    resetZoom();
  } else {
    // Zoom into the click point.
    const rect = els.lightboxImg.getBoundingClientRect();
    const cx = e.clientX - (rect.left + rect.width / 2);
    const cy = e.clientY - (rect.top + rect.height / 2);
    const scale = 2.5;
    state.zoom = { scale, x: -cx * (scale - 1), y: -cy * (scale - 1) };
    els.lightboxStage.classList.add("zoomed");
    applyTransform();
  }
}

function onWheel(e) {
  e.preventDefault();
  const delta = -e.deltaY * 0.0015;
  const next = clamp(state.zoom.scale * (1 + delta), 1, 6);
  if (next === state.zoom.scale) return;
  state.zoom.scale = next;
  if (next === 1) {
    state.zoom.x = 0;
    state.zoom.y = 0;
    els.lightboxStage.classList.remove("zoomed");
  } else {
    els.lightboxStage.classList.add("zoomed");
  }
  applyTransform();
}

function bindPan() {
  let dragging = false;
  let startX = 0, startY = 0, startTX = 0, startTY = 0;

  const onDown = (e) => {
    if (state.zoom.scale <= 1) return;
    if (e.target.closest(".lightbox-bar")) return;
    dragging = true;
    const pt = pointer(e);
    startX = pt.x; startY = pt.y;
    startTX = state.zoom.x; startTY = state.zoom.y;
    els.lightboxStage.classList.add("panning");
    e.preventDefault();
  };
  const onMove = (e) => {
    if (!dragging) return;
    const pt = pointer(e);
    state.zoom.x = startTX + (pt.x - startX);
    state.zoom.y = startTY + (pt.y - startY);
    applyTransform();
  };
  const onUp = () => {
    if (!dragging) return;
    dragging = false;
    els.lightboxStage.classList.remove("panning");
  };

  els.lightboxStage.addEventListener("mousedown", onDown);
  window.addEventListener("mousemove", onMove);
  window.addEventListener("mouseup", onUp);
  els.lightboxStage.addEventListener("touchstart", onDown, { passive: false });
  window.addEventListener("touchmove", onMove, { passive: false });
  window.addEventListener("touchend", onUp);
}

function pointer(e) {
  if (e.touches && e.touches[0]) return { x: e.touches[0].clientX, y: e.touches[0].clientY };
  return { x: e.clientX, y: e.clientY };
}

function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

// --------- Share & download ---------

async function shareCurrent() {
  if (!state.current) return;
  const url = absoluteUrl(`#${state.current.id}`);
  const title = `${state.current.region_display} - ${state.current.theme_display}`;
  const text = `${title} · grid2poster`;
  if (navigator.share) {
    try {
      await navigator.share({ title, text, url });
      return;
    } catch (err) {
      if (err && err.name === "AbortError") return;
    }
  }
  try {
    await navigator.clipboard.writeText(url);
    showToast("Link copied to clipboard");
  } catch (err) {
    showToast(url);
  }
}

function triggerDownload(href, name) {
  const a = document.createElement("a");
  a.href = href;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

function absoluteUrl(hash) {
  const u = new URL(window.location.href);
  u.hash = hash.startsWith("#") ? hash.slice(1) : hash;
  return u.toString();
}

let toastTimer = null;
function showToast(msg) {
  els.toast.textContent = msg;
  els.toast.hidden = false;
  requestAnimationFrame(() => els.toast.classList.add("visible"));
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    els.toast.classList.remove("visible");
    setTimeout(() => { els.toast.hidden = true; }, 200);
  }, 1800);
}
